spring:
  profiles: prod
databases:
  db_users:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://10.5.121.117:5432/auth
    username: postgres
    password: postgres
  db_oauth2_mongo:
    url: 127.0.0.1:27017
    username: admin
    password: adminpassword
config:
  users: db_users
  mongo_oauth2: db_oauth2_mongo
